version: "3.4"
services:
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    links:
      - backend
      - node_backend
    # depends_on: [backend]

  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

    command: gunicorn -b 0.0.0.0:5000 wsgi:app

  # node
  node_backend:
    build: ./node_backend
    ports:
      - 3000:3000

  frontend:
    build: ./e_comm_front
    ports:
      - 80:8000
    links:
      - backend
      - node_backend

volumes:
  mongo-data:
  mongo-configdb:
# docker-compose up --build
# docker compose up -d backend database
