version: "3.8"
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    # depends_on: [backend]

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    links:
      - database
    command: gunicorn -b 0.0.0.0:5000 wsgi:app

  frontend:
    build: ./e_comm_front
    ports:
      - 80:8000
    links:
      - backend

volumes:
  mongo-data:
  mongo-configdb:
# docker-compose up --build
